export const COURSE_LIST_REQUEST="COURSE_LIST_REQUEST"
export const COURSE_LIST_SUCCESS="COURSE_LIST_SUCCESS"
export const COURSE_LIST_FAIL="COURSE_LIST_FAIL"
export const COURSE_CLEAR="COURSE_CLEAR"

export const COURSE_DELETE_REQUEST="COURSE_DELETE_REQUEST"
export const COURSE_DELETE_SUCCESS="COURSE_DELETE_SUCCESS"
export const COURSE_DELETE_FAIL="COURSE_DELETE_FAIL"

export const COURSE_ADD_REQUEST="COURSE_ADD_REQUEST"
export const COURSE_ADD_SUCCESS="COURSE_ADD_SUCCESS"
export const COURSE_ADD_FAIL="COURSE_ADD_FAIL"

export const COURSE_EDIT_REQUEST="COURSE_EDIT_REQUEST"
export const COURSE_EDIT_SUCCESS="COURSE_EDIT_SUCCESS"
export const COURSE_EDIT_FAIL="COURSE_EDIT_FAIL"


